"""add email and password to customer

Revision ID: ac885e78eb81
Revises: efecf3234485
Create Date: 2026-01-07 18:43:06.650457

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac885e78eb81"
down_revision: Union[str, Sequence[str], None] = "efecf3234485"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email and password columns to customers table
    op.add_column(
        "customers", sa.Column("email", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "customers",
        sa.Column("password", sa.String(), nullable=False, server_default=""),
    )

    # Remove server_default, it's only for migration
    op.alter_column("customers", "email", server_default=None)
    op.alter_column("customers", "password", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "password")
    op.drop_column("customers", "email")
    # ### end Alembic commands ###
